'\" t
.\"     Title: darkradiant
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 07/06/2018
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "DARKRADIANT" "1" "07/06/2018" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
darkradiant \- the level editor for The Dark Mod
.SH "SYNOPSIS"
.sp
darkradiant [ options ] filename
.SH "DESCRIPTION"
.sp
DarkRadiant is a level editor for The Dark Mod\&. It loads and saves Doom 3\-format *\&.map files, making use of assets within a game installation tree\&.
.SH "OPTIONS"
.PP
\fB\-\-disable\-sound\fR
.RS 4
Disable the sound manager module\&. This may be useful if there are problems with sound devices on the system\&.
.RE
.PP
\fIfilename\fR
.RS 4
Path to a map file to load\&. This may be either an absolute filesystem path, or a mod\-local path\&.
.RE
.sp
In order to allow maximum customisability by after\-market mods, the id software game engines use a three\-directory system: the \fIbase\fR directory, which is where the core game assets are installed, and then two mod\-specific directories known as \fIfs_game\fR and \fIfs_game_base\fR\&. The intention is that \fIfs_game_base\fR is used for the common mod assets, and \fIfs_game\fR is available for individual map authors to further customise assets used in their own releases\&.
.sp
When editing Dark Mod missions, typically \fIfs_game_base\fR would be set to "darkmod", with \fIfs_game\fR either left blank or set to the value associated with a particular map author\(cqs own release\&.
.sp
These values are normally configured in preferences, but they can be overridden on the command line if required:
.PP
\fBfs_game=\fR\fB\fIgame\fR\fR
.RS 4
Override the configured fs_game value\&.
.RE
.PP
\fBfs_game_base=\fR\fB\fIgame_base\fR\fR
.RS 4
Override the configured fs_game_base value\&.
.RE
.SH "BUGS"
.sp
The lighting render mode is very limited compared to the Doom 3 rendering system\&. In particular, there are no stencil shadows, foglights or any other complex lighting effects\&.
.SH "AUTHOR"
.sp
DarkRadiant is developed by the Dark Mod team, at http://www\&.thedarkmod\&.com
