#pragma once

#include "iorthoview.h"
#include "icameraview.h"
#include "math/Vector2.h"
#include "math/Vector3.h"

namespace ui
{

// Base class for a generic event to be handled by the MouseTool implementation
class MouseToolEvent
{
private:
    // The device position (in pixels, left upper corner is 0,0)
    Vector2 _devicePosition;

    // The device delta for tools using a frozen mouse pointer
    Vector2 _deviceDelta;

    IInteractiveView& _view;

public:
    MouseToolEvent(IInteractiveView& view, const Vector2& devicePosition) :
        _devicePosition(devicePosition),
        _deviceDelta(0, 0),
        _view(view)
    {}

    MouseToolEvent(IInteractiveView& view, const Vector2& devicePosition, const Vector2& delta) :
        _deviceDelta(delta),
        _view(view)
    {}

    virtual ~MouseToolEvent() {}

    // Returns the mouse position in pixels
    const Vector2& getDevicePosition() const
    {
        return _devicePosition;
    }

    // Used by MouseMove events, this contains the delta
    // in device coordinates since the last mousemove event
    const Vector2& getDeviceDelta() const
    {
        return _deviceDelta;
    }

    IInteractiveView& getInteractiveView()
    {
        return _view;
    }
};

// Special event subtype for XY View events. Provides
// information about view type, for example.
class XYMouseToolEvent :
    public MouseToolEvent
{
private:
    IOrthoView& _view;

    // Current mouse coordinates, relative to 0,0,0 world origin
    Vector3 _worldPos;

public:
    XYMouseToolEvent(IOrthoView& view, const Vector3& worldPos, const Vector2& devicePos) :
        MouseToolEvent(view, devicePos),
        _worldPos(worldPos),
        _view(view)
    {}

    XYMouseToolEvent(IOrthoView& view, const Vector3& worldPos, const Vector2& devicePos, const Vector2& delta) :
        MouseToolEvent(view, devicePos, delta),
        _view(view)
    {}

    IOrthoView& getView()
    {
        return _view;
    }

    const Vector3& getWorldPos() const
    {
        return _worldPos;
    }

    EViewType getViewType() const
    {
        return _view.getViewType();
    }

    float getScale() const
    {
        return _view.getScale();
    }
};

// Special type for events generated by the camera view.
class CameraMouseToolEvent :
    public MouseToolEvent
{
private:
    ICameraView& _view;

public:
    CameraMouseToolEvent(ICameraView& view, const Vector2& devicePos) :
        MouseToolEvent(view, devicePos),
        _view(view)
    {}

    CameraMouseToolEvent(ICameraView& view, const Vector2& devicePos, const Vector2& delta) :
        MouseToolEvent(view, devicePos, delta),
        _view(view)
    {}

    ICameraView& getView()
    {
        return _view;
    }
};

} // namespace
